### ISSUE TITLE
Is this extension outdated?

### ISSUE THREAD

**Issue by bnjbvr** [sn-extensions/simple-markdown-editor#1]
Hi! I'm trying to set up this extension on my server, and I'm running into a few issues:

- first, the permission request should be sent **per message** and it is not, although the parent iframe listener seems to expect it when receiving a message posted by the extension.
- the addon seems to request the permission first by sending a message of type `request-permissions`, but this is not handled by the parent (at least in https://github.com/standardnotes/web as far as I can see)
- then, the `ComponentManager.onReady` function is crashing because the `data` it's passed doesn't have an `environment`, or `uuid`.

Am I missing something here? Is the code outdated, or not in sync with https://github.com/standardnotes/web at least?

Thanks for your answer and for making StandardNotes, it's really nice.

**Comment by mobitar** [comment]
Hey, sorry for the confusion. Actually, the code you're looking at now is very new code :) So new that it doesn't yet interact with the master branch on the web repo. You should be looking at the "packages" (or v2.1) branch on web. This is an all new (internally) component system which uses the code that is already deployed to master on all the extension repos. This is because I'm gearing up to launch 2.1 some time this month.

Sorry for the confusion. Going forward, check out the packages branch to better understand components and extensions. It'll be merged into master pretty soon.

**Comment by bnjbvr** [comment]
I think I got it: the extensions are already using the code that's on the `packages` branch of the web server, so my issue is invalid. (If that's not true, can you correct me, please?) Thanks!

**Comment by bnjbvr** [comment]
(hah, mid-air collision 🙂 Thanks for confirming!)

**Comment by mobitar** [comment]
:) And to address the permissions issue, the new method by which components seek permission is to essentially just perform an action, and the componentsManager will deduce the necessary permissions. You can still do it the old way, but this way is easier since you don't have to explicitly request anything.

**Comment by mobitar** [comment]
Oh and lastly, extensions on 2.1 can be installed offline, so you might not even need to set it up on your own server (unless you plan on accessing it from the web). More info here: https://github.com/standardnotes/forum/issues/152
